/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI3 */

#ifndef _Included_JNI3
#define _Included_JNI3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI3
 * Method:    getNum
 * Signature: (II)[C
 */
JNIEXPORT jcharArray JNICALL Java_JNI3_getNum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
